security:
  encoders:
    Symfony\Component\Security\Core\User\User: plaintext
  firewalls:
    secured_area:
      pattern: ^/
      anonymous: ~
      form_login:
        login_path: /login
        check_path: /login_check
  providers:
    in_memory:
      memory:
        users:
          ryan: { password: ryanpass, roles: 'ROLE_USER' }
          admin: { password: kitten, roles: 'ROLE_ADMIN' }